# Generated by Django 4.2.7 on 2023-12-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_surverysubmit_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surverysubmit',
            name='season',
            field=models.CharField(choices=[('summer', 'Summer'), ('spring', 'Spring'), ('winter', 'Winter'), ('fall', 'Fall')], default='summer', max_length=30),
        ),
    ]
