# Generated by Django 4.2.7 on 2023-12-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_alter_surverysubmit_areas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surverysubmit',
            name='areas',
            field=models.CharField(choices=[('putting', 'Putting'), ('approuching', 'Approuching'), ('driving', 'Driving'), ('chipping', 'Chipping'), ('idk', 'IDK')], default='putting', max_length=30),
        ),
    ]
